#AndroidCS: enforce UTF-8 & locale for Gradle daemon
#Fri Sep 25 01:06:25 GMT 2026
android.dependency.useConstraints=false
android.enableR8.fullMode=true
android.injected.testOnly=false
android.nonTransitiveRClass=true
android.r8.optimizedResourceShrinking=true
android.r8.strictFullModeForKeepRules=false
android.uniquePackageNames=false
android.useAndroidX=true
kotlin.code.style=official
kotlin.incremental=true
kotlin.incremental.js=true
kotlin.parallel.tasks.in.project=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=true
org.gradle.daemon=true
org.gradle.daemon.idletimeout=10800000
org.gradle.jvmargs=-Xmx4096m -Xms2048m -XX\:+UseG1GC -XX\:SoftRefLRUPolicyMSPerMB\=50 -XX\:MaxMetaspaceSize\=1024m -XX\:ReservedCodeCacheSize\=256m -XX\:+HeapDumpOnOutOfMemoryError -Dfile.encoding\=UTF-8
org.gradle.parallel=true
org.gradle.tooling.parallel=true
org.gradle.vfs.watch=true
org.gradle.workers.max=4
systemProp.file.encoding=UTF-8
systemProp.sun.jnu.encoding=UTF-8
systemProp.user.country=US
systemProp.user.language=en
